name: Generate Datas

on:
  schedule: # executar a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Atualizar dados
    runs-on: ubuntu-latest
    steps:
      # Etapa 1: Gerar a animação da grade de contribuições do GitHub
      - name: Gerar grade de contribuições
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: esmsena  # Substitua pelo seu nome de usuário GitHub
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Etapa 2: Implante no GitHub Pages
      - name: Implante no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
